apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: production
spec:
  containers:
    - name: nginx-2
      image: nginx
    - name: alpine
      image: nginx
    - name: nginx
      image: nginx