apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: my-app-replicaset
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
      name: my-app-pod
      labels:
        app: my-app-pod
        type: front-end
    spec:
      containers:
        - name: nginx-2
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end